## Default
baseURL = "https://milan.bykoga.com/"
theme = "milan-theme"

## Localization

## Pages
disableKinds = ["taxonomy", "term"]

## Media
# https://www.webfx.com/tools/emoji-cheat-sheet/
enableEmoji = true

[markup.goldmark.renderer]
    unsafe= true