[pt-br]
    home = "/pt-br"
    LanguageName = "pt-br"
    title = "bykoga"
    weight = 2
    dateFormat = "15:04 - 02/01/06"
    shortDateFormat = "02/01/06"
    shortestDateFormat = "02/01"
    contentDir = "content/portugues"
    [pt-br.Taxonomies]
        topic = "topicos"
    [pt-br.menu]    
        [[pt-br.menu.main]]
            weight = 0
            name = "Início"
            url = "/"
        [[pt-br.menu.main]]
            weight = 10
            name = "Sobre"
            url = "/sobre/"
        [[pt-br.menu.main]]
            weight = 15
            name = "Portfólio"
            url = "/portfolio/"
        [[pt-br.menu.main]]
            weight = 20
            name = "Tópicos"
            identifier = "topics"
            [[pt-br.menu.main]]
                parent = "topics"
                weight = 0
                name = "Arte"
                url = "/arte"
            [[pt-br.menu.main]]
                parent = "topics"
                weight = 5
                name = "Crônicas"
                url = "/cronicas"
            [[pt-br.menu.main]]
                parent = "topics"
                weight = 10
                name = "Game Dev"
                url = "/gamedev"
            [[pt-br.menu.main]]
                parent = "topics"
                weight = 20
                name = "Jornal"
                url = "/jornal"

[en]
    home = "/en"
    LanguageName = "en"
    title = "bykoga"
    weight = 1
    dateFormat = "15:04 - Jan 2, 06"
    shortDateFormat = "Jan 2, 06"
    shortestDateFormat = "Jan 2"
    diaryStartFormat = "January"
    diaryEndFormat = "2"
    contentDir = "content/english"
    [en.Taxonomies]
        topic = "topics"
    [en.menu]
        [[en.menu.main]]
            name = "Home"
            url = "/"
            weight = 0
        [[en.menu.main]]
            name = "About"
            url = "/about/"
            weight = 10
        [[en.menu.main]]
            weight = 15
            name = "Portfolio"
            url = "/portfolio/"
        [[en.menu.main]]
            weight = 20
            name = "Topics"
            identifier = "topics"
            [[en.menu.main]]
                parent = "topics"
                weight = 0
                name = "Art"
                url = "/art"
            [[en.menu.main]]
                parent = "topics"
                weight = 5
                name = "Chronicles"
                url = "/chronicles"
            [[en.menu.main]]
                parent = "topics"
                weight = 10
                name = "Game Dev"
                url = "/gamedev"
            [[en.menu.main]]
                parent = "topics"
                weight = 20
                name = "Journal"
                url = "/journal"